### PR TITLE
Fix handling of empty Hash values

### PR DESCRIPTION
**Pull request by chisholm**
Fix the postset_hook for Hash so it allows empty hashes without crashing.

Related: #320.

### CODE REVIEW

**Comment by clenk** [comment]
Feel free to remove the py26 environment. Something like this line might fix the py34 environment: https://github.com/oasis-open/cti-stix-elevator/pull/163/files#diff-b91f3d5bd63fcd17221b267e851608e8R12

**Comment by chisholm** [comment]
The problem with using tox tricks is that that isn't how people will be installing the library for real use.  The library's declared requirements need to be accurate, or they'll have a broken installation.  Those tricks seem more appropriate for testing different *valid* combinations of libraries.  Correct me if I'm wrong, but the commit you referenced will ensure the tox tests pass, but if someone just 'pip installs' the library, it won't look at the tox config so they'll get the wrong version of lxml and a broken installation.  One hopes that tox config change was paired with an update to setup.py or related.

**Comment by clenk** [comment]
True, good point; the lxml version limit should go in setup.py.

**Comment by chisholm** [comment]
One more small question: should py33 be in the tox envlist?  It's not included in travis tests.

**Comment by clenk** [comment]
No, we don't need to support 3.3 any more. Looks like it wasn't fully removed. The list of Python versions in `classifiers` in setup.py also needs updating.

**Comment by chisholm** [comment]
Done.

**Pull request merged**
