### PR TITLE
Update CIQ extension to use mixbox. Fix #260.

### LINKED ISSUE #260: CIQ Address extension non mixboxified
I think the `cybox.extensions.location.ciq_address_3_0` module was left out of the mixboxification effort.

### PR DESCRIPTION
**Pull request by gtback**
I added a basic test to verify the extension works, but not much more than that. The test is pretty fragile, but better than nothing.

@bworrell: If you're OK with this, go ahead and merge. Otherwise, let me know what else you were planning as part of #260.

### CODE REVIEW

**Comment by gtback** [comment]
Bah! I can fix the errors on py32, py33, py34 by using six.StringIO, but I don't know what to do about RHEL6.
- Skip the test entirely on in rhel6?
- Bump the required version of LXML package-wide?

Thoughts?

**Comment by bworrell** [comment]
Maybe for now we just exclude the test in rhel6 and see what comes of #266. We might be able to fix this by dropping lxml.

**Comment by gtback** [comment]
Thanks, @bworrell. I ended up using some hackery to skip the test. I couldn't just use `skipTest()` without more hackery.

**Comment by bworrell** [comment]
Haha, I figured you were going to use the `--exclude` option for `nose` in our `tox.ini` file. Something like:

```ini
[testenv:rhel6]
basepython=python2.6
commands =
    nosetests cybox --exclude="ciq_test.py"
deps =
    lxml==2.2.3
    mixbox>=0.0.7
    python-dateutil==1.4.1
    nose
```

I'm not sure if that'd work at all but it's kinda how i was thinking about skipping it for rhel6.

**Comment by gtback** [comment]
Oh, I didn't know about that. Oops.

**Comment by gtback** [comment]
Updated in 370e540c689c7bff649c5da7e804616ff4dddd76

**Pull request merged**
