### PR TITLE
Update WhoisRegistrantInfoType in bindings.

### LINKED ISSUE #227: Whois Object is missing the Fax_Number parameter in the binding interface
The __init__() operation of of the WhoIsRegistrantInfoType in the bindings interface is missing the Fax_Number and the Organization parameter in python-cybox 2.1.0.8 and 2.1.0.9.  Both parameters appears to be found in the __init__() of the WhoisContactType from which the WhoIsRegistrantInfoType inherits.

If one generates stubs from the current XML schema and trys to use the stubs against the python-cybox binding interface there will received the error 

super(WhoisRegistrantInfoTypeSub, self).__init__(contact_type, Contact_ID, Name, Email_Address, Phone_Number, Fax_Number, Address, Organization, Registrant_ID, )
TypeError: __init__() takes at most 8 arguments (10 given)

### PR DESCRIPTION
**Pull request by gtback**
Fix #227

### CODE REVIEW

**Comment by gtback** [comment]
@CyberDaedalus00 I think this should fix the problem; would you be able to check and make sure it is what you intended?

@bworrell / @ikiril01 a second set of eyes on this would be great, too!

**Comment by ikiril01** [comment]
@gtback looks good to me! Thanks :)

**Comment by gtback** [comment]
Thanks, @ikiril01

**Comment by CyberDaedalus00** [comment]
Looks correct to me as well

**Pull request merged**
